spring:
  datasource:
    url: jdbc:mysql://localhost:3306/family_tree
    username: dbuser #dbuser
    password: dbpass #dbpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: username # username email
    password: password # password email
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8084

app:
  jwt-secret: "8d00c1da9078aa59b425b1a26b87f9d3c5e575658614857ed7d2c162b63c215f"
  jwt-expiration: 86400000
